name: Laravel Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, ctype, json, tokenizer, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM dependencies and build Vite
        run: |
          npm ci
          npm run build

      - name: Laravel Optimize
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Zip contents for deployment
        run: |
          zip -r release.zip . -x ".git/*" "node_modules/*" "tests/*" "storage/*.log" ".github/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'adminv2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
